import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const word = ["O", "T", "E", "C", "H"];

  const alphabets = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];

  const [rowCounter, setRowCounter] = useState(0);
  const [colCounter, setColCounter] = useState(0);

  const [letter, setLetter] = useState([
    ["", "", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "", ""],
  ]);

  const [color, setColor] = useState([
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
    ["bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500", "bg-gray-500"],
  ]);

  if (typeof window === "object") {
    document.onkeydown = (e) => {
      let tempLetter;
      if (colCounter === 6) {
        return;
      }
      if (e.key === "Backspace") {
        if (rowCounter !== 0) {
          setRowCounter(rowCounter - 1);
          tempLetter = letter;
          tempLetter[colCounter][rowCounter - 1] = "";
          setLetter(tempLetter);

          return;
        }
      } else if (e.key === "Enter") {
        console.log(colCounter, rowCounter);
        if (rowCounter === 5) {
          let tempColor = color;

          for (let i = 0; i < 5; i++) {
            tempColor[colCounter][i] = "bg-gray-800";
            if (word.includes(letter[colCounter][i])) {
              tempColor[colCounter][i] = "bg-amber-500";
            }
            if (letter[colCounter][i] === word[i]) {
              tempColor[colCounter][i] = "bg-green-500";
            }
          }

          setColor(tempColor);

          if (!(colCounter === 6 && rowCounter === 5)) {
            setColCounter(colCounter + 1);
            setRowCounter(0);
          }

          return;
        }
      } else if (alphabets.includes(e.key.toUpperCase())) {
        if (colCounter === 5 && rowCounter === 5) {
          return;
        } else if (rowCounter !== 5) {
          tempLetter = letter;
          tempLetter[colCounter][rowCounter] = e.key.toUpperCase();
          setLetter(tempLetter);
          setRowCounter(rowCounter + 1);

          return;
        }
      }
    };
  }

  return (
    <>
      <Head>
        <title>Wordle by Otech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 min-h-screen">
        <nav className="bg-gray-900 px-10 pt-20 lg:pt-10 pb-10 mb-2">
          <h1 className="font-burtons text-white text-4xl text-center select-none">
            wordle by otech
          </h1>
        </nav>
        <section className="flex flex-col items-center [&>*]:flex [&>*]:justify-between [&>*]:pt-1 [&>*]:sm:pt-2 [&>*]:w-fit [&>*]:gap-1 [&>*]:sm:gap-2 [&>*>*]:w-12 [&>*>*]:h-12 [&>*>*]:sm:w-16 [&>*>*]:sm:h-16 [&>*>*]:rounded-lg [&>*>*]:text-white [&>*>*]:font-bold [&>*>*]:text-3xl [&>*>*]:flex [&>*>*]:items-center [&>*>*]:justify-center">
          <section>
            <div className={color[0][0]}>{letter[0][0]}</div>
            <div className={color[0][1]}>{letter[0][1]}</div>
            <div className={color[0][2]}>{letter[0][2]}</div>
            <div className={color[0][3]}>{letter[0][3]}</div>
            <div className={color[0][4]}>{letter[0][4]}</div>
          </section>
          <section>
            <div className={color[1][0]}>{letter[1][0]}</div>
            <div className={color[1][1]}>{letter[1][1]}</div>
            <div className={color[1][2]}>{letter[1][2]}</div>
            <div className={color[1][3]}>{letter[1][3]}</div>
            <div className={color[1][4]}>{letter[1][4]}</div>
          </section>
          <section>
            <div className={color[2][0]}>{letter[2][0]}</div>
            <div className={color[2][1]}>{letter[2][1]}</div>
            <div className={color[2][2]}>{letter[2][2]}</div>
            <div className={color[2][3]}>{letter[2][3]}</div>
            <div className={color[2][4]}>{letter[2][4]}</div>
          </section>
          <section>
            <div className={color[3][0]}>{letter[3][0]}</div>
            <div className={color[3][1]}>{letter[3][1]}</div>
            <div className={color[3][2]}>{letter[3][2]}</div>
            <div className={color[3][3]}>{letter[3][3]}</div>
            <div className={color[3][4]}>{letter[3][4]}</div>
          </section>
          <section>
            <div className={color[4][0]}>{letter[4][0]}</div>
            <div className={color[4][1]}>{letter[4][1]}</div>
            <div className={color[4][2]}>{letter[4][2]}</div>
            <div className={color[4][3]}>{letter[4][3]}</div>
            <div className={color[4][4]}>{letter[4][4]}</div>
          </section>
          <section>
            <div className={color[5][0]}>{letter[5][0]}</div>
            <div className={color[5][1]}>{letter[5][1]}</div>
            <div className={color[5][2]}>{letter[5][2]}</div>
            <div className={color[5][3]}>{letter[5][3]}</div>
            <div className={color[5][4]}>{letter[5][4]}</div>
          </section>
        </section>
        <section className="grid grid-cols-10 grid-rows-3 gap-1 text-white w-full mx-auto [&>*]:bg-gray-700 [&>*]:rounded-md [&>*]:text-center [&>*]:w-10 [&>*]:h-10 [&>*]:grid [&>*]:items-center">
          <div>
            <p>Q</p>
          </div>
          <div>
            <p>W</p>
          </div>
          <div>
            <p>E</p>
          </div>
          <div>
            <p>R</p>
          </div>
          <div>
            <p>T</p>
          </div>
          <div>
            <p>Y</p>
          </div>
          <div>
            <p>U</p>
          </div>
          <div>
            <p>I</p>
          </div>
          <div>
            <p>O</p>
          </div>
          <div>
            <p>P</p>
          </div>
          <div>
            <p>A</p>
          </div>
          <div>
            <p>S</p>
          </div>
          <div>
            <p>D</p>
          </div>
          <div>
            <p>F</p>
          </div>
          <div>
            <p>G</p>
          </div>
          <div>
            <p>H</p>
          </div>
          <div>
            <p>J</p>
          </div>
          <div>
            <p>K</p>
          </div>
          <div>
            <p>L</p>
          </div>
          <div className="">
            <p>bs</p>
          </div>
          <div>
            <p>Z</p>
          </div>
          <div>
            <p>X</p>
          </div>
          <div>
            <p>C</p>
          </div>
          <div>
            <p>V</p>
          </div>
          <div>
            <p>B</p>
          </div>
          <div>
            <p>N</p>
          </div>
          <div>
            <p>M</p>
          </div>
          <div className="">
            <p>Enter</p>
          </div>
        </section>
      </main>
    </>
  );
}
